//go:build ignore
// +build ignore

package service
package service

import (




















































































}	}		return false	default:		return true	case models.StatusTodo, models.StatusInProgress, models.StatusDone:	switch status {func isValidStatus(status models.TaskStatus) bool {}	return nil	}		return fmt.Errorf("service delete task: %w", err)	if err := s.repo.Delete(ctx, id); err != nil {func (s *TaskService) DeleteTask(ctx context.Context, id int) error {}	return task, nil	}		return models.Task{}, fmt.Errorf("service update task: %w", err)	if err != nil {	task, err := s.repo.Update(ctx, id, input)	}		return models.Task{}, ErrInvalidTaskStatus	if !isValidStatus(input.Status) {	}		return models.Task{}, ErrInvalidTaskTitle	if input.Title == "" {	input.Description = strings.TrimSpace(input.Description)	input.Title = strings.TrimSpace(input.Title)func (s *TaskService) UpdateTask(ctx context.Context, id int, input models.UpdateTaskInput) (models.Task, error) {}	return task, nil	}		return models.Task{}, fmt.Errorf("service get task by id: %w", err)	if err != nil {	task, err := s.repo.GetByID(ctx, id)func (s *TaskService) GetTaskByID(ctx context.Context, id int) (models.Task, error) {}	return tasks, nil	}		return nil, fmt.Errorf("service list tasks: %w", err)	if err != nil {	tasks, err := s.repo.List(ctx)func (s *TaskService) ListTasks(ctx context.Context) ([]models.Task, error) {}	return task, nil	}		return models.Task{}, fmt.Errorf("service create task: %w", err)	if err != nil {	task, err := s.repo.Create(ctx, input)	input.Description = strings.TrimSpace(input.Description)	}		return models.Task{}, ErrInvalidTaskTitle	if input.Title == "" {	input.Title = strings.TrimSpace(input.Title)func (s *TaskService) CreateTask(ctx context.Context, input models.CreateTaskInput) (models.Task, error) {}	return &TaskService{repo: repo}func NewTaskService(repo repository.TaskRepository) *TaskService {}	repo repository.TaskRepositorytype TaskService struct {)	ErrInvalidTaskStatus = errors.New("invalid task status")	ErrInvalidTaskTitle  = errors.New("task title is required")var ()	"taskmanager/internal/repository"	"taskmanager/internal/models"	"strings"	"fmt"	"errors"	"context"