//go:build ignore
// +build ignore

package handlers















































































































































}	_ = json.NewEncoder(w).Encode(payload)	w.WriteHeader(status)	w.Header().Set("Content-Type", "application/json")func writeJSON(w http.ResponseWriter, status int, payload any) {}	return id, true	}		return 0, false		writeJSON(w, http.StatusBadRequest, map[string]string{"error": "invalid task id"})	if err != nil || id <= 0 {	id, err := strconv.Atoi(idText)	idText := chi.URLParam(r, "id")func parseIDParam(w http.ResponseWriter, r *http.Request) (int, bool) {}	w.WriteHeader(http.StatusNoContent)	}		return		writeJSON(w, http.StatusInternalServerError, map[string]string{"error": "failed to delete task"})		}			return			writeJSON(w, http.StatusNotFound, map[string]string{"error": "task not found"})		if errors.Is(err, repository.ErrTaskNotFound) {	if err := h.taskService.DeleteTask(r.Context(), id); err != nil {	}		return	if !ok {	id, ok := parseIDParam(w, r)func (h *TaskHandler) DeleteTask(w http.ResponseWriter, r *http.Request) {}	writeJSON(w, http.StatusOK, task)	}		return		}			writeJSON(w, http.StatusInternalServerError, map[string]string{"error": "failed to update task"})		default:			writeJSON(w, http.StatusBadRequest, map[string]string{"error": err.Error()})		case errors.Is(err, service.ErrInvalidTaskTitle), errors.Is(err, service.ErrInvalidTaskStatus):			writeJSON(w, http.StatusNotFound, map[string]string{"error": "task not found"})		case errors.Is(err, repository.ErrTaskNotFound):		switch {	if err != nil {	task, err := h.taskService.UpdateTask(r.Context(), id, input)	}		return		writeJSON(w, http.StatusBadRequest, map[string]string{"error": "invalid request body"})	if err := json.NewDecoder(r.Body).Decode(&input); err != nil {	var input models.UpdateTaskInput	}		return	if !ok {	id, ok := parseIDParam(w, r)func (h *TaskHandler) UpdateTask(w http.ResponseWriter, r *http.Request) {}	writeJSON(w, http.StatusOK, task)	}		return		writeJSON(w, http.StatusInternalServerError, map[string]string{"error": "failed to get task"})		}			return			writeJSON(w, http.StatusNotFound, map[string]string{"error": "task not found"})		if errors.Is(err, repository.ErrTaskNotFound) {	if err != nil {	task, err := h.taskService.GetTaskByID(r.Context(), id)	}		return	if !ok {	id, ok := parseIDParam(w, r)func (h *TaskHandler) GetTask(w http.ResponseWriter, r *http.Request) {}	writeJSON(w, http.StatusOK, tasks)	}		return		writeJSON(w, http.StatusInternalServerError, map[string]string{"error": "failed to list tasks"})	if err != nil {	tasks, err := h.taskService.ListTasks(r.Context())func (h *TaskHandler) ListTasks(w http.ResponseWriter, r *http.Request) {}	writeJSON(w, http.StatusCreated, task)	}		return		writeJSON(w, http.StatusInternalServerError, map[string]string{"error": "failed to create task"})		}			return			writeJSON(w, http.StatusBadRequest, map[string]string{"error": err.Error()})		if errors.Is(err, service.ErrInvalidTaskTitle) {	if err != nil {	task, err := h.taskService.CreateTask(r.Context(), input)	}		return		writeJSON(w, http.StatusBadRequest, map[string]string{"error": "invalid request body"})	if err := json.NewDecoder(r.Body).Decode(&input); err != nil {	var input models.CreateTaskInputfunc (h *TaskHandler) CreateTask(w http.ResponseWriter, r *http.Request) {}	})		r.Delete("/{id}", h.DeleteTask)		r.Put("/{id}", h.UpdateTask)		r.Get("/{id}", h.GetTask)		r.Get("/", h.ListTasks)		r.Post("/", h.CreateTask)	r.Route("/tasks", func(r chi.Router) {func (h *TaskHandler) RegisterRoutes(r chi.Router) {}	return &TaskHandler{taskService: taskService}func NewTaskHandler(taskService *service.TaskService) *TaskHandler {}	taskService *service.TaskServicetype TaskHandler struct {)	"taskmanager/internal/service"	"taskmanager/internal/repository"	"taskmanager/internal/models"	"github.com/go-chi/chi/v5"	"strconv"	"net/http"	"errors"	"encoding/json"import (package handlers